// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtjGdSGXVFLfkaihidGfNGV-_V7kAxlcw',
    appId: '1:126364852802:web:387aff5031edc2bcdf83db',
    messagingSenderId: '126364852802',
    projectId: 'hackathon-89524',
    authDomain: 'hackathon-89524.firebaseapp.com',
    storageBucket: 'hackathon-89524.appspot.com',
    measurementId: 'G-CKH4G4T056',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuarmf99YgBCW7JIyYmU1grBCC6DlaAeU',
    appId: '1:126364852802:android:530938169fbfbd31df83db',
    messagingSenderId: '126364852802',
    projectId: 'hackathon-89524',
    storageBucket: 'hackathon-89524.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqVCvd0NVjxxCCkeHltiDpJXHooqQZC4w',
    appId: '1:126364852802:ios:8911167eb61d037adf83db',
    messagingSenderId: '126364852802',
    projectId: 'hackathon-89524',
    storageBucket: 'hackathon-89524.appspot.com',
    iosBundleId: 'com.example.iotapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqVCvd0NVjxxCCkeHltiDpJXHooqQZC4w',
    appId: '1:126364852802:ios:8911167eb61d037adf83db',
    messagingSenderId: '126364852802',
    projectId: 'hackathon-89524',
    storageBucket: 'hackathon-89524.appspot.com',
    iosBundleId: 'com.example.iotapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtjGdSGXVFLfkaihidGfNGV-_V7kAxlcw',
    appId: '1:126364852802:web:fc0142cf55a617f2df83db',
    messagingSenderId: '126364852802',
    projectId: 'hackathon-89524',
    authDomain: 'hackathon-89524.firebaseapp.com',
    storageBucket: 'hackathon-89524.appspot.com',
    measurementId: 'G-YRLZPBVK9F',
  );
}
